# Generated by Django 3.0.5 on 2020-04-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='Empresa',
            new_name='empresa',
        ),
    ]
